services:
  server:
    build:
      context: ./server
      dockerfile: ./.dockerfiles/Dockerfile
      args:
        UBUNTU_VERSION: '22.04'
        LOGIN_USER: 'docker'
        WORKSPACE: '/home/docker/.autotesting'
    image: markus-autotest-server-dev:1.2.0
    volumes:
      - ./server:/app:cached
      - workspace:/home/docker/.autotesting:rw
    environment:
      - REDIS_URL=redis://redis:6379/
      - WORKSPACE=/home/docker/.autotesting
      - SUPERVISOR_URL=127.0.0.1:9001
      - AUTOTESTER_CONFIG=/app/.dockerfiles/docker-config.yml
      - STACK_ROOT=/home/docker/.autotesting/.stack
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: ./client
      dockerfile: ./.dockerfiles/Dockerfile
      args:
        UBUNTU_VERSION: '22.04'
    image: markus-autotest-client-dev:1.2.0
    container_name: 'autotest-client'
    volumes:
      - ./client:/app:cached
    environment:
      - REDIS_URL=redis://redis:6379/
      - FLASK_HOST=0.0.0.0
    ports:
      - '5000:5001'
    depends_on:
      - redis
      - server
    networks:
      - default
      - markus_dev

  postgres:
    image: postgres:14
    volumes:
      - postgres_autotest:/var/lib/postgresql/data
    environment:
      - PSQL_HISTFILE=/root/log/.psql_history
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '45432:5432'

  redis:
    image: redis:7
    volumes:
      - redis_autotest:/data
    ports:
      - 6379

  rq_dashboard:
    image: eoranged/rq-dashboard
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/
    ports:
      - '9181:9181'
    depends_on:
      - redis

volumes:
  postgres_autotest:
  redis_autotest:
  workspace:

networks:
  markus_dev:
    name: markus_dev
    external: true
